#!/bin/sh
rm daisyKernels.cl.bin
cd $PROJ
export OMP_NUM_THREADS=8
g++ -I$PROJ/include -I/usr/local/cuda/include\
    -fopenmp -lOpenCL -ljpeg -lpng -lgtk-x11-2.0\
    -fno-strict-aliasing \
    -Wall -fPIC -O3 \
    -DHAVE_INLINE -DGSL_RANGE_CHECK_OFF -DWITH_PNG -DWITH_JPEG \
    src/daisy/main.cpp src/kutility/image_io_bmp.cpp \
    src/kutility/image_io_png.cpp src/kutility/image_io_pnm.cpp \
    src/kutility/image_io_jpeg.cpp src/kutility/image_manipulation.cpp \
    src/kutility/interaction.cpp src/kutility/general.cpp src/ocl/cachedConstructs.cpp \
    src/ocl/cachedProgram.cpp src/daisy/oclDaisy.cpp src/daisy/oclDaisySearch.cpp src/daisy/general.cpp `pkg-config --cflags --libs opencv` -o src/daisy/gdaisy
